### ISSUE TITLE
pod version is not updated ?

### ISSUE THREAD

**Issue by brieucdlf** [gregttn/CheckmarkSegmentedControl#1]
Hey,

It seems that the pod version of the class is not up to date for swift 2.0.. Got 4 errors on the class file.
Correct me if I'm wrong :)

Thank you, nice class btw :)

**Comment by gregttn** [comment]
Hi,

Hmmm... I've just tested the control and everything seems to be working ok for me with the newest pod version 0.1.1, Xcode 7.2.1 and 9.2 deployment target.

What are the errors you are getting?

**Comment by dsenese** [comment]
I am getting the same issue. Her are the errors showing up.

CheckmarkSegmentedControl.swift:245:32: 'Printable' has been renamed to 'CustomStringConvertible'

CheckmarkSegmentedControl.swift:220:26: Method does not override any method from its superclass

CheckmarkSegmentedControl.swift:66:15: A non-failable initializer cannot chain to failable initializer 'init(coder:)' written with 'init?'

CheckmarkSegmentedControl.swift:83:38: 'sorted' is unavailable: call the 'sort()' method on the array

**Comment by dsenese** [comment]
They're simple fixes but you might want to update them for 2.0! Nice job though 👍

**Comment by gregttn** [comment]
Thanks!
Yes, it is time to update this to the newest Swift version.
I will get this done soon.

**Comment by gregttn** [comment]
I had a look at this again and realised that I actually fixed those issues already. They are fixed in the 0.1.1 version. 
I believe that you might have a cached version of the pod (version 0.1.0). You can check that with:

`pod cache list`

The pod can be deleted from cache with:
`pod cache clean CheckmarkSegmentedControl`

You can also force it to use the correct version in your Podfile:

`pod 'CheckmarkSegmentedControl', '0.1.1'`

Let me know if that worked for you.

**Comment by bmbrina** [comment]
Hi, I also had those errors and created a PR that resolves them. Nice work on the pod!

**Comment by dsenese** [comment]
I got it working okay with the changes I made! I'm not sure why I got the 0.1 version when installing the pod though.

**Comment by gregttn** [comment]
@bmbrina Thanks for the PR but I believe it addresses different issue than the one mentioned in here.
The issues that @dsenese had were fixed in this [commit](https://github.com/gregttn/CheckmarkSegmentedControl/commit/c5d06579c0a2e4dd1530085887d85772a0b96e08)

I believe that the problems were due to cached pod. I checked on two different macs now and all works as expected.

**Comment by brieucdlf** [comment]
Works for me ! Thank you for everything !

**Comment by gregttn** [comment]
Looks resolved. Closing
